server.port=9000
spring.thymeleaf.cache=false

#--------AS400-------------------------------------------------
# Configuración del Driver de AS400
spring.datasource.url=jdbc:as400://PUB400.com;prompt=false;naming=sql;errors=full
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.ibm.as400.access.AS400JDBCDriver

# Configuración del Pool (HikariCP)
# Máximo de conexiones simultáneas abiertas
spring.datasource.hikari.maximum-pool-size=10
# Tiempo máximo de espera para obtener una conexión (ms)
spring.datasource.hikari.connection-timeout=20000
# Nombre para monitorear el pool
spring.datasource.hikari.pool-name=As400HikariPool
#--------------------------------------------------------------